data:
  train_csv: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/WSI_experiments/train.csv'
  tune_csv: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/WSI_experiments/tune.csv'
  test_csv: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/WSI_experiments/test.csv'

features_dir: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/WSI_experiments/4096_HIPT_TCGA_ckpt/features/global/slide'
output_dir: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/WSI_experiments/4096_HIPT_TCGA_ckpt/classification_experiments'
experiment_name: 'colon_examode_binary_classification_TCGA'
level: 'global'

nepochs: 50
num_classes: 2
label_name: 'label'
label_encoding:
label_mapping: 


task: 'classification'
loss: 'ce'
loss_options:
  num_classes: ${num_classes}

training:
  batch_size: 1
  pct:
  weighted_sampling: True
  gradient_accumulation: 32

tuning:
  batch_size: 1
  tune_every: 1

testing:
  retrieve_checkpoint: 'best'

model:
  pretrain_vit_patch: '/data/pathology/projects/pathology-self-supervision/checkpoint_hipt/vit256_small_dino.pth'
  freeze_vit_patch: True
  freeze_vit_patch_pos_embed: True
  pretrain_vit_region: '/data/pathology/projects/pathology-self-supervision/checkpoint_hipt/vit4k_xs_dino.pth'
  freeze_vit_region: True
  freeze_vit_region_pos_embed: True
  region_size: 4096
  patch_size: 256
  mini_patch_size: 16
  dropout: 0.25
  agg_method: 'concat'
  slide_pos_embed:
    use: False
    learned: False
    type: '1d'
    max_seq_len: 512
    max_nslide: 21
    tile_size: ${model.region_size}

optim:
  name: 'adam'
  lr: 0.0002
  wd: 0.00001
  lr_scheduler:
    name: 'step'
    step_size: 50
    gamma: 0.5

early_stopping:
  enable: False
  tracking: 'loss'
  min_max: 'min'
  patience: 10
  min_epoch: 30
  save_all: False

wandb:
  enable: True
  project: 'HIPT_subtyping'
  username: 'sofialeoncontreras'
  exp_name: '${experiment_name}'
  dir: '/data/pathology/projects/pathology-self-supervision/'
  to_log: ['loss', 'auc', 'kappa', 'roc_auc_curve']
  group:

hydra:
  run:
    dir: /tmp/hydra_output