region_dir: '/home/user/code/git/clemsgrs/hs2p/output/tcga_brca_survival_debug/patches/'

output_dir: 'output/tcga_brca_survival_debug'
experiment_name: 'feature_extraction'
resume: False

slide_list:

region_size: 4096
patch_size: 256
mini_patch_size: 16

format: 'jpg'
level: 'global'
save_region_features: False
num_workers: 4

pretrain_vit_patch: 'checkpoints/vit_256_small_dino.pth'
pretrain_vit_region: 'checkpoints/vit_4096_xs_dino.pth'

wandb:
  enable: False
  project: 'hipt'
  username: 'clemsg'
  exp_name: '${experiment_name}'
  dir: '/home/user/'
  group:

hydra:
  run:
    dir: /tmp/hydra_output