train_csv: '/data/pathology/projects/ais-cap/dataset/panda/hipt/dino/downstream_task/2-class/train.csv'
test_csv: '/data/pathology/projects/ais-cap/dataset/panda/hipt/dino/downstream_task/2-class/test.csv'

label_name: 'label'

load_features: False
save_features: False
features_dir: 'output/debug/knn'

batch_size_per_gpu: 20
nb_knn: [1, 3, 5, 10, 20, 100]
temperature: 0.07

model:
  arch: 'vit_small'
  patch_size: 16
  pretrained_weights: '/data/pathology/projects/ais-cap/dataset/panda_radboud/hipt/checkpoints/vit_256_small_dino.pth'
  checkpoint_key: 'teacher'

speed:
  use_cuda: True
  num_workers: 4
