hdf5_files_csv: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/non_cancer_lgd_region_4096.csv'
wsi_files: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/slide_paths_csv/non_cancer_lgd_slides.csv'
output_dir: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/region_4096_h5/'
processed_wsi_csv: '/data/pathology/projects/pathology-self-supervision/data/examode_colon/processed_wsi2region_h5.csv'
tissue: 'colon_non_cancer_lgd'

region_2_patches:
  patch_size: 256
